# Generated by Django 4.2 on 2023-04-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemovies',
            old_name='custom_name',
            new_name='custom_title',
        ),
        migrations.RenameField(
            model_name='favoritemovies',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='favoriteplanets',
            old_name='planet_id',
            new_name='planet',
        ),
    ]
